### ISSUE TITLE
First image in all list of browsed gallery and after selection shows white part not actual image.

### ISSUE THREAD

**Issue by vyomacredencys** [yazeed44/MultiImagePicker#1]
Hi,
Thanks a lot for great library. 
I am facing an issue while browsing gallery. First image is always not get load , even selecting sub folder shows 1st image as blank white. And many times it shows all sublist as blank white , which later might or might not get refresh.
How ccan I get that working?

Thanks.

**Comment by yazeed44** [comment]
It's true some times there are problems with loading , but not with the first one

have you tried it on another device ?

**Comment by vyomacredencys** [comment]
Yah, tried in moto g and Samsung grand. in both same issue occurs.

**Comment by yazeed44** [comment]
Could you give me more details about system (version and stuff) so i can try it in the emulator ?

**Comment by gaurangtalati** [comment]
Hi yazeed44,
Actually I am working on the same project with "vyomacredencys".. 
Right now we have actually implemented your library on android version of Jellybean, Kitkat and Lollipop. All are having the same issues.
One more thing, as we scrolls the list , images tends to refresh every time. 
So could you help us out and let us where we must do the changes so that this thing should be prevented from happening.

**Comment by yazeed44** [comment]
https://github.com/yazeed44/MultiImagePicker/blob/master/library/src/main/java/net/yazeed44/imagepicker/ImagesAdapter.java

try to comment setHeight(final View convertView) and see what happens

**Comment by yazeed44** [comment]
Solved with latest commits
